"""add test_history and convert test to boolean

Revision ID: 166024720669
Revises: e0fa43c0f38d
Create Date: 2022-05-12 17:47:49.727732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '166024720669'
down_revision = 'e0fa43c0f38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_history',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('fact_id', sa.Integer(), nullable=True),
                    sa.Column('correct', sa.Boolean(), nullable=False),
                    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.ForeignKeyConstraint(['fact_id'], ['fact.fact_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_test_history_id'), 'test_history', ['id'], unique=False)
    op.drop_column('fact', 'test_mode')
    op.add_column('fact', sa.Column('test_mode', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact', 'test_mode')
    op.add_column('fact', sa.Column('test_mode', sa.SMALLINT(), nullable=False, server_default='0'))
    op.drop_index(op.f('ix_test_history_id'), table_name='test_history')
    op.drop_table('test_history')
    # ### end Alembic commands ###
