"""Create creation_date col in studyset

Revision ID: 19a191ff920c
Revises: 5226e60d1987
Create Date: 2022-05-27 23:19:32.861669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a191ff920c'
down_revision = '5226e60d1987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studyset', sa.Column('create_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studyset', 'create_date')
    # ### end Alembic commands ###
