"""add log value post test

Revision ID: 23e1f44f4f62
Revises: 7a86599a211c
Create Date: 2023-10-30 02:37:31.719564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e1f44f4f62'
down_revision = '7a86599a211c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE log ADD VALUE 'get_post_test_facts'")
    op.execute("ALTER TYPE log ADD VALUE 'post_test_study'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
