"""Add test mode column

Revision ID: 2ee368bbc6f6
Revises: 03d8017f5307
Create Date: 2021-06-17 17:19:09.428462

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2ee368bbc6f6'
down_revision = '03d8017f5307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_mode', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_mode')
    # ### end Alembic commands ###
