"""add deck, fact, history, suspended, user, user_deck models

Revision ID: 465dc0d727bd
Revises: d4867f3a4c0a
Create Date: 2020-04-25 07:12:07.075217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465dc0d727bd'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_id'), 'deck', ['id'], unique=False)
    op.create_index(op.f('ix_deck_title'), 'deck', ['title'], unique=False)
    op.create_table('fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('front', sa.String(), nullable=False),
    sa.Column('back', sa.String(), nullable=False),
    sa.Column('create_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('answer_lines', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_back'), 'fact', ['back'], unique=False)
    op.create_index(op.f('ix_fact_front'), 'fact', ['front'], unique=False)
    op.create_index(op.f('ix_fact_id'), 'fact', ['id'], unique=False)
    op.create_table('user_deck',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'deck_id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.Enum('study', 'suspend', 'delete', 'report', 'unsuspend', 'undo_delete', 'resolve_report', 'undo_study', name='log'), nullable=False),
    sa.Column('repetition_model', sa.Enum('leitner', 'sm2', 'karl', name='repetition'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['fact_id'], ['fact.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_id'), 'history', ['id'], unique=False)
    op.create_table('suspended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_suspended', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('report', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['fact.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspended_id'), 'suspended', ['id'], unique=False)
    op.drop_index('ix_item_description', table_name='item')
    op.drop_index('ix_item_id', table_name='item')
    op.drop_index('ix_item_title', table_name='item')
    op.drop_table('item')
    op.add_column('user', sa.Column('default_deck_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('repetition_model', sa.Enum('leitner', 'sm2', 'karl', name='repetition'), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_full_name', table_name='user')
    op.create_foreign_key(None, 'user', 'deck', ['default_deck_id'], ['id'])
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'username')
    op.drop_column('user', 'repetition_model')
    op.drop_column('user', 'default_deck_id')
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    op.create_index('ix_item_title', 'item', ['title'], unique=False)
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    op.create_index('ix_item_description', 'item', ['description'], unique=False)
    op.drop_index(op.f('ix_suspended_id'), table_name='suspended')
    op.drop_table('suspended')
    op.drop_index(op.f('ix_history_id'), table_name='history')
    op.drop_table('history')
    op.drop_table('user_deck')
    op.drop_index(op.f('ix_fact_id'), table_name='fact')
    op.drop_index(op.f('ix_fact_front'), table_name='fact')
    op.drop_index(op.f('ix_fact_back'), table_name='fact')
    op.drop_table('fact')
    op.drop_index(op.f('ix_deck_title'), table_name='deck')
    op.drop_index(op.f('ix_deck_id'), table_name='deck')
    op.drop_table('deck')
    # ### end Alembic commands ###
