"""rename study_set to studyset and create session_deck

Revision ID: 47a0d502a95a
Revises: 139df0683d97
Create Date: 2022-05-16 02:11:11.782600

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '47a0d502a95a'
down_revision = '139df0683d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_deck',
                    sa.Column('studyset_id', sa.Integer(), nullable=False),
                    sa.Column('deck_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
                    sa.ForeignKeyConstraint(['studyset_id'], ['studyset.id'], ),
                    sa.PrimaryKeyConstraint('studyset_id', 'deck_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_deck')
    # ### end Alembic commands ###
