"""rename correct to response for consistency

Revision ID: 47fe14c79175
Revises: 166024720669
Create Date: 2022-05-14 01:11:52.755163

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '47fe14c79175'
down_revision = '166024720669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_history', sa.Column('response', sa.Boolean(), nullable=False))
    op.drop_column('test_history', 'correct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_history', sa.Column('correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('test_history', 'response')
    # ### end Alembic commands ###
