"""add separate reported and deleted tables

Revision ID: 491383f70589
Revises: 9afc4e3a9bf3
Create Date: 2020-06-26 05:23:30.267933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '491383f70589'
down_revision = '9afc4e3a9bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_deleted', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['fact.fact_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_id'), 'deleted', ['id'], unique=False)
    op.create_table('reported',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_reported', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('suggestion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['fact_id'], ['fact.fact_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reported_id'), 'reported', ['id'], unique=False)
    op.drop_column('suspended', 'comment')
    op.drop_column('suspended', 'suspend_type')
    op.drop_column('suspended', 'suggestion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suspended', sa.Column('suggestion', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('suspended', sa.Column('suspend_type', postgresql.ENUM('delete', 'suspend', 'report', name='suspendtype'), autoincrement=False, nullable=False))
    op.add_column('suspended', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_reported_id'), table_name='reported')
    op.drop_table('reported')
    op.drop_index(op.f('ix_deleted_id'), table_name='deleted')
    op.drop_table('deleted')
    # ### end Alembic commands ###
