"""add log types for test mode

Revision ID: 4afdb8d415dd
Revises: 4c4de690e32f
Create Date: 2021-06-18 17:59:17.091617

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4afdb8d415dd'
down_revision = '4c4de690e32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE log ADD VALUE 'test_study'")
    op.execute("ALTER TYPE log ADD VALUE 'get_test_facts'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
