"""add log update_user

Revision ID: 4c116a99c4ee
Revises: df7ea91f1589
Create Date: 2022-07-08 17:11:30.328345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c116a99c4ee'
down_revision = 'df7ea91f1589'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TYPE log ADD VALUE 'update_user'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
