"""add show tip

Revision ID: 4cb1bd466ce1
Revises: d39b49c62b4f
Create Date: 2020-07-21 02:05:38.737593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb1bd466ce1'
down_revision = 'd39b49c62b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwa_tip', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pwa_tip')
    # ### end Alembic commands ###
