"""change test mode to int

Revision ID: 57667899ac6f
Revises: 2ee368bbc6f6
Create Date: 2021-06-18 17:04:17.860490

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '57667899ac6f'
down_revision = '2ee368bbc6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_mode')
    op.add_column('user', sa.Column('test_mode', sa.SmallInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_mode')
    op.add_column('user', sa.Column('test_mode', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###
