"""add rationale column

Revision ID: 6872aa796f4a
Revises: 6af85811ee88
Create Date: 2022-05-22 21:11:44.142967

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6872aa796f4a'
down_revision = '6af85811ee88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_deck_deck_type'), 'deck', ['deck_type'], unique=False)
    op.drop_index('ix_deck_public', table_name='deck')
    op.add_column('session_fact', sa.Column('rationale', sa.String(), nullable=True))
    op.add_column('studyset', sa.Column('debug_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studyset', 'debug_id')
    op.drop_column('session_fact', 'rationale')
    op.create_index('ix_deck_public', 'deck', ['deck_type'], unique=False)
    op.drop_index(op.f('ix_deck_deck_type'), table_name='deck')
    # ### end Alembic commands ###
