"""convert bool to enum

Revision ID: 6af85811ee88
Revises: edb59940cef6
Create Date: 2022-05-19 14:20:06.609946

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '6af85811ee88'
down_revision = 'edb59940cef6'
branch_labels = None
depends_on = None

decktype_enum = postgresql.ENUM('default', 'public', 'hidden', name='decktype')


# using clause: https://stackoverflow.com/questions/29069506/alembic-alter-column-type-with-using
# https://github.com/sqlalchemy/alembic/issues/278
# https://www.munderwood.ca/index.php/2015/05/28/altering-postgresql-columns-from-one-enum-to-another/
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    decktype_enum.create(op.get_bind())
    op.alter_column('deck', 'public',
                    existing_type=sa.BOOLEAN(),
                    type_=decktype_enum,
                    existing_nullable=False,
                    new_column_name='deck_type',
                    postgresql_using="(CASE public::text WHEN 'true' then 'public' WHEN 'false' then 'default' ELSE public::text END)::decktype")
    op.create_index(op.f('ix_deck_public'), 'deck', ['deck_type'], unique=False)
    op.create_index(op.f('ix_studyset_is_test'), 'studyset', ['is_test'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studyset_is_test'), table_name='studyset')
    op.drop_index(op.f('ix_deck_public'), table_name='deck')
    op.alter_column('deck', 'deck_type',
                    existing_type=decktype_enum,
                    type_=sa.BOOLEAN(),
                    new_column_name='public',
                    existing_nullable=False,
                    postgresql_using="(CASE deck_type::text WHEN 'public' then 'true' WHEN 'default' then 'false' WHEN 'hidden' then 'false' ELSE deck_type::text END)::boolean")
    # ### end Alembic commands ###
