"""rename test_mode to new_test_mode

Revision ID: 6c00659b79c1
Revises: 4afdb8d415dd
Create Date: 2021-06-19 17:05:45.039087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c00659b79c1'
down_revision = '4afdb8d415dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('next_test_mode', sa.SmallInteger(), nullable=False, server_default=sa.text("'0'::smallint")))
    op.drop_column('user', 'test_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_mode', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False))
    op.drop_column('user', 'next_test_mode')
    # ### end Alembic commands ###
