"""Add show_mnemonic_help column to user table

Revision ID: 7c432afcbe9e
Revises: d30ad91b8772
Create Date: 2024-02-28 01:22:43.397472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c432afcbe9e'
down_revision = 'd30ad91b8772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('show_mnemonic_help', sa.Boolean(), nullable=True, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'show_mnemonic_help')
    # ### end Alembic commands ###
