"""is_correct should be nullable, create new correct column

Revision ID: 7e169b59629a
Revises: 47a0d502a95a
Create Date: 2022-05-16 04:32:56.617688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e169b59629a'
down_revision = '47a0d502a95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('correct', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_history_correct'), 'history', ['correct'], unique=False)
    op.drop_index('ix_history_is_correct', table_name='history')
    op.drop_column('history', 'is_correct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('is_correct', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_index('ix_history_is_correct', 'history', ['is_correct'], unique=False)
    op.drop_index(op.f('ix_history_correct'), table_name='history')
    op.drop_column('history', 'correct')
    # ### end Alembic commands ###
