"""remove next_test_mode and last_test_date columns

Revision ID: 94625a55cb65
Revises: 19a191ff920c
Create Date: 2022-06-15 20:04:19.400986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94625a55cb65'
down_revision = '19a191ff920c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'next_test_mode')
    op.drop_column('user', 'last_test_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_test_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('next_test_mode', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
