"""add retired column

Revision ID: 957c6698b8e2
Revises: 6872aa796f4a
Create Date: 2022-05-23 15:49:05.045968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957c6698b8e2'
down_revision = '6872aa796f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studyset', sa.Column('retired', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studyset', 'retired')
    # ### end Alembic commands ###
