"""add suggestion and comment to suspended

Revision ID: 9afc4e3a9bf3
Revises: e3a211187158
Create Date: 2020-06-25 21:56:53.066974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9afc4e3a9bf3'
down_revision = 'e3a211187158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suspended', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('suspended', sa.Column('suggestion', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suspended', 'suggestion')
    op.drop_column('suspended', 'comment')
    # ### end Alembic commands ###
