"""remove repetition_model from history (put in details)

Revision ID: ae31c23bebdf
Revises: 250c2f90374e
Create Date: 2020-04-28 20:01:09.686488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae31c23bebdf'
down_revision = '250c2f90374e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'repetition_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('repetition_model', postgresql.ENUM('leitner', 'sm2', 'karl', name='repetition'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
