"""history fact.id should be optional

Revision ID: b7b8acac9d4f
Revises: ffdf470fe0ba
Create Date: 2020-06-17 19:31:18.958679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b8acac9d4f'
down_revision = 'ffdf470fe0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'fact_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'fact_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
