"""rename session to studyset

Revision ID: bcd5eab43566
Revises: c15cf3a0a3f8
Create Date: 2022-05-14 15:41:31.805204

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bcd5eab43566'
down_revision = 'c15cf3a0a3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studyset',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('deck_id', sa.Integer(), nullable=True),
                    sa.Column('is_test', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['deck_id'], ['fact.fact_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_studyset_deck_id'), 'studyset', ['deck_id'], unique=False)
    op.create_index(op.f('ix_studyset_id'), 'studyset', ['id'], unique=False)
    op.create_index(op.f('ix_studyset_is_test'), 'studyset', ['is_test'], unique=False)
    op.create_index(op.f('ix_studyset_user_id'), 'studyset', ['user_id'], unique=False)
    op.drop_index('ix_session_deck_id', table_name='session')
    op.drop_index('ix_session_id', table_name='session')
    op.drop_index('ix_session_is_test', table_name='session')
    op.drop_index('ix_session_user_id', table_name='session')
    op.drop_constraint('session_fact_session_id_fkey', 'session_fact', type_='foreignkey')
    op.drop_table('session')
    op.add_column('session_fact', sa.Column('studyset_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'session_fact', 'studyset', ['studyset_id'], ['id'])
    op.drop_column('session_fact', 'session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_fact', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session_fact', type_='foreignkey')
    op.create_foreign_key('session_fact_session_id_fkey', 'session_fact', 'session', ['session_id'], ['id'])
    op.drop_column('session_fact', 'studyset_id')
    op.create_table('session',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('deck_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('is_test', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['deck_id'], ['fact.fact_id'], name='session_deck_id_fkey'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='session_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='session_pkey')
                    )
    op.create_index('ix_session_user_id', 'session', ['user_id'], unique=False)
    op.create_index('ix_session_is_test', 'session', ['is_test'], unique=False)
    op.create_index('ix_session_id', 'session', ['id'], unique=False)
    op.create_index('ix_session_deck_id', 'session', ['deck_id'], unique=False)
    op.drop_index(op.f('ix_studyset_user_id'), table_name='studyset')
    op.drop_index(op.f('ix_studyset_is_test'), table_name='studyset')
    op.drop_index(op.f('ix_studyset_id'), table_name='studyset')
    op.drop_index(op.f('ix_studyset_deck_id'), table_name='studyset')
    op.drop_table('studyset')
    # ### end Alembic commands ###
