"""create indices, session and session_fact

Revision ID: c15cf3a0a3f8
Revises: 47fe14c79175
Create Date: 2022-05-14 03:29:47.976803

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c15cf3a0a3f8'
down_revision = '47fe14c79175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('deck_id', sa.Integer(), nullable=True),
                    sa.Column('is_test', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['deck_id'], ['fact.fact_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_session_deck_id'), 'session', ['deck_id'], unique=False)
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.create_index(op.f('ix_session_is_test'), 'session', ['is_test'], unique=False)
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_table('session_fact',
                    sa.Column('session_id', sa.Integer(), nullable=False),
                    sa.Column('fact_id', sa.Integer(), nullable=False),
                    sa.Column('history_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['fact_id'], ['fact.fact_id'], ),
                    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
                    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
                    sa.PrimaryKeyConstraint('session_id', 'fact_id')
                    )
    op.alter_column('fact', 'test_mode',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    existing_server_default=sa.text('false'))
    op.add_column('history', sa.Column('is_correct', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index(op.f('ix_history_fact_id'), 'history', ['fact_id'], unique=False)
    op.create_index(op.f('ix_history_is_correct'), 'history', ['is_correct'], unique=False)
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_index(op.f('ix_test_history_response'), 'test_history', ['response'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_history_response'), table_name='test_history')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_index(op.f('ix_history_is_correct'), table_name='history')
    op.drop_index(op.f('ix_history_fact_id'), table_name='history')
    op.drop_column('history', 'is_correct')
    op.alter_column('fact', 'test_mode',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    existing_server_default=sa.text('false'))
    op.drop_table('session_fact')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_index(op.f('ix_session_is_test'), table_name='session')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_index(op.f('ix_session_deck_id'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
