"""add indices

Revision ID: c8bcaad53b52
Revises: 36fb79f5f33e
Create Date: 2020-06-14 01:33:50.548139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bcaad53b52'
down_revision = '36fb79f5f33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fact_category'), 'fact', ['category'], unique=False)
    op.create_index(op.f('ix_fact_deck_id'), 'fact', ['deck_id'], unique=False)
    op.create_index(op.f('ix_fact_identifier'), 'fact', ['identifier'], unique=False)
    op.create_index(op.f('ix_fact_user_id'), 'fact', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_user_id'), table_name='fact')
    op.drop_index(op.f('ix_fact_identifier'), table_name='fact')
    op.drop_index(op.f('ix_fact_deck_id'), table_name='fact')
    op.drop_index(op.f('ix_fact_category'), table_name='fact')
    # ### end Alembic commands ###
