"""add public and fact-user relationship

Revision ID: cd3f4ab7777e
Revises: 465dc0d727bd
Create Date: 2020-04-25 18:12:06.893455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd3f4ab7777e'
down_revision = '465dc0d727bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact', sa.Column('answer', sa.String(), nullable=False))
    op.add_column('fact', sa.Column('public', sa.Boolean(), nullable=False))
    op.add_column('fact', sa.Column('text', sa.String(), nullable=False))
    op.alter_column('fact', 'create_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('fact', 'update_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('fact', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_fact_answer'), 'fact', ['answer'], unique=False)
    op.create_index(op.f('ix_fact_text'), 'fact', ['text'], unique=False)
    op.drop_index('ix_fact_back', table_name='fact')
    op.drop_index('ix_fact_front', table_name='fact')
    op.drop_column('fact', 'back')
    op.drop_column('fact', 'front')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact', sa.Column('front', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('fact', sa.Column('back', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_fact_front', 'fact', ['front'], unique=False)
    op.create_index('ix_fact_back', 'fact', ['back'], unique=False)
    op.drop_index(op.f('ix_fact_text'), table_name='fact')
    op.drop_index(op.f('ix_fact_answer'), table_name='fact')
    op.alter_column('fact', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fact', 'update_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('fact', 'create_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('fact', 'text')
    op.drop_column('fact', 'public')
    op.drop_column('fact', 'answer')
    # ### end Alembic commands ###
