"""create mnemonic table

Revision ID: e1488e104d80
Revises: f007a4240a14
Create Date: 2023-10-14 17:50:03.985012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1488e104d80'
down_revision = 'f007a4240a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mnemonic',
    sa.Column('id', sa.Integer(), nullable=False, index=True),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_mnemonic', sa.Boolean(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('is_offensive', sa.Boolean(), nullable=True),
    sa.Column('is_incorrect_definition', sa.Boolean(), nullable=True),
    sa.Column('is_difficult_to_understand', sa.Boolean(), nullable=True),
    sa.Column('is_bad_keyword_link', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('correct', sa.Boolean(), index=True),
    sa.ForeignKeyConstraint(['fact_id'], ['fact.fact_id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studyset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_table('mnemonic')
    pass
