"""is_test shouldn't be int, convert to bool

Revision ID: edb59940cef6
Revises: 7e169b59629a
Create Date: 2022-05-16 05:07:01.805238

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'edb59940cef6'
down_revision = '7e169b59629a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studyset', 'is_test')
    op.add_column('studyset', sa.Column('is_test', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                                        nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('studyset', 'is_test')
    op.add_column('studyset',
                  sa.Column('is_test', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
