"""add enum values

Revision ID: f007a4240a14
Revises: 4c116a99c4ee
Create Date: 2022-08-04 21:57:35.267113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f007a4240a14'
down_revision = '4c116a99c4ee'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("COMMIT")
    op.execute("ALTER TYPE repetition ADD VALUE 'karl'")
    op.execute("ALTER TYPE repetition ADD VALUE 'settles'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
