"""add show_help to user

Revision ID: fdcf07aac389
Revises: 491383f70589
Create Date: 2020-07-03 00:34:16.915740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdcf07aac389'
down_revision = '491383f70589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('show_help', sa.Boolean(), nullable=True, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'show_help')
    # ### end Alembic commands ###
